### PR TITLE
Hostmanager entries required in different section

### PR DESCRIPTION
**Pull request by datenbrille**
The entries of the host manager plugin section needed in the head of the vagrant file. Otherwise they have no effect.

### CODE REVIEW

**Comment by datenbrille** [comment]
I will work on this next week. I will rename the variable.

**Comment by lennartstein** [comment]
Any news on this?

**Comment by ThYpHo0n** [comment]
Hey guys,

I want to finally close this PR and finish a working hostmanager implementation here. As far as I understood correct the only problem at the moment on this branch is the indention but I think the place of the hostmanager configuration lines should be outside the config.vm.define block. Which is not the case at the moment. It should work in the block but doesn't look very good in my pov.
Any thoughts on this?

**Comment by lennartstein** [comment]
Hey Niklas,

No there are several issues with this PR. The indention is just a readability issue, but how the host manager plugin is now building the entries for aliases is not correct. 
1. Since InVaDE is multi-machine compatible, it would now setup the hostmanager plugin for all machines at once. As I said before in my comments, just the option "hostmanager.enabled" should be in the top of the Vagrantfile (outside of the machine definitions you mentioned before). BUT all definitions like "hostmanager.aliases" should be inside the machine definition.
2. With the new commit of this PR InVaDE would require the hostmanager plugin. This should not be the case since you should also be able to use it without this plugin. 
3. Indention. To understand the Vagrantfile it's necessary to read it. 

I'm also planning to refactor the code to easily implement new Vagrant Plugins support.

**Comment by lennartstein** [comment]
I updated the plugin and implemented everything what was needed. 
So update the plugin with **vagrant plugin update vagrant-invade** to get the newest version **0.5.2.**

**Comment by ThYpHo0n** [comment]
Thank you very much! I just had prepared some stuff in my branch which I can now happily throw away :)

**Comment by lennartstein** [comment]
You're very welcome! 
If there are any other feature requests just open an issue for it. Greetings to everyone of the InnoGames crew of your team. :-)

**Pull request closed without merging**
